name: SYNK scan
on: 
  push:
    branches: ["choonyee"]

jobs:
   SYNK-scan:
     runs-on: ubuntu-latest
     environment: 
       name: dev

     steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: ap-southeast-1

         - name: Login to Amazon ECR
           id: login-ecr
           uses: aws-actions/amazon-ecr-login@v1

         - uses: actions/checkout@v2
         - name: Run Snyk to scan Docker image for vulnerabilities
           uses: snyk/actions/docker@master
           env:
             SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
           with:
             image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_S3 }}:${{ github.sha }}
             args: --severity-threshold=critical --report