name: SYNK scan
on: 
  push:
    branches: ["choonyee"]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with: 
          aws-region: ap-southeast-1

      - name: Run Snyk to scan Docker image for vulnerabilities
        run: snyk test --docker ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_S3 }}:latest --file=path/to/Dockerfile --severity-threshold=critical --report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
