name: SYNK scan
on: 
  push:
    branches: ["choonyee"]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with: 
          aws-region: ap-southeast-1

      - name: Debug ECR Registry
        run: echo "ECR Registry: ${{ steps.login-ecr.outputs.registry }}"

      - name: Debug Snyk Image URI
        run: echo "Snyk Image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_S3 }}:${{ github.sha }}"

      - name: Run Snyk to scan Docker image for vulnerabilities
        uses: snyk/actions/docker@v1.0.0  # Use a specific version like v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_S3 }}:${{ github.sha }}
          args: --severity-threshold=critical --report --debug
